---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.mongodb.name}}
spec:
  serviceName: mongodb
  replicas: {{.Values.spec.replicas}}
  selector:
    matchLabels:
{{- .Values.labels | toYaml | nindent 6 }}
  template:
    metadata:
      labels:
{{- .Values.labels | toYaml | nindent 8 }}
    spec:
      nodeSelector:
{{- .Values.nodeselector | toYaml | nindent 8 }}
      containers:
        - name: {{.Values.containers.name}}
          image: {{.Values.containers.image}}:{{.Values.containers.tag}}
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort}}
              name: {{.Values.containers.ports.name}}
          resources:
            requests:
              cpu: {{.Values.containers.resources.requests.cpu}}
              memory: {{.Values.containers.resources.requests.memory}}
            limits:
              cpu: {{.Values.containers.resources.limits.cpu}}
              memory: {{.Values.containers.resources.limits.memory}}
          livenessProbe:
            exec:
              command:
                - mongo
                - "--eval"
                - db.runCommand('ping').ok
            initialDelaySeconds: {{.Values.containers.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.containers.livenessProbe.periodSeconds}}
            timeoutSeconds: {{.Values.containers.livenessProbe.timeoutSeconds}}
            failureThreshold: {{.Values.containers.livenessProbe.failureThreshold}}
          readinessProbe:
            exec:
              command:
                - mongo
                - "--eval"
                - db.runCommand('ping').ok
            initialDelaySeconds: {{.Values.containers.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.containers.readinessProbe.periodSeconds}}
            timeoutSeconds: {{.Values.containers.readinessProbe.timeoutSeconds}}
            failureThreshold: {{.Values.containers.readinessProbe.failureThreshold}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
    - port: {{.Values.service.ports.port}}
  selector:
{{- .Values.labels | toYaml | nindent 4}}
  type: {{.Values.service.type}}